# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GFLYcKBYbRE6KjLlQSOIUc2pEQJCwN6U
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

# ---------------------------------------------------
# TWO DEGREE OF FREEDOM VIBRATION SYSTEM WITH DAMPING
# Governing Equation:
# m*x¨ + c*x˙ + k*x = 0
# ---------------------------------------------------

# Define the ODE system
def damped_system_ode(y, t, m1, m2, k1, k2, k3, c1, c2):

    # State variables
    x1, v1, x2, v2 = y

    # -----------------------------
    # Equations for Mass 1
    # -----------------------------

    # Velocity equation
    dx1dt = v1

    # Acceleration equation with damping
    dv1dt = (
        -c1 * v1                  # damping force
        -k1 * x1                  # spring 1 force
        -k2 * (x1 - x2)           # coupling spring force
    ) / m1

    # -----------------------------
    # Equations for Mass 2
    # -----------------------------

    dx2dt = v2

    dv2dt = (
        -c2 * v2                  # damping force
        -k3 * x2                  # spring 3 force
        -k2 * (x2 - x1)           # coupling spring force
    ) / m2

    return [dx1dt, dv1dt, dx2dt, dv2dt]


# ---------------------------------------------------
# SYSTEM PARAMETERS
# ---------------------------------------------------

m1 = 5.0
m2 = 10.0

k1 = 2.0
k2 = 2.0
k3 = 2.0

# Damping coefficients
c1 = 1.5
c2 = 1.5

# ---------------------------------------------------
# INITIAL CONDITIONS
# [x1, v1, x2, v2]
# ---------------------------------------------------

initial_conditions = [1.0, 0.0, 0.0, 0.0]

# ---------------------------------------------------
# TIME ARRAY
# ---------------------------------------------------

t = np.linspace(0, 30, 1000)

# ---------------------------------------------------
# SOLVE THE ODEs
# ---------------------------------------------------

solution_damped = odeint(
    damped_system_ode,
    initial_conditions,
    t,
    args=(m1, m2, k1, k2, k3, c1, c2)
)

# ---------------------------------------------------
# EXTRACT DISPLACEMENTS
# ---------------------------------------------------

x1_damped = solution_damped[:, 0]
x2_damped = solution_damped[:, 2]

# ---------------------------------------------------
# ORIGINAL UNDAMPED TWO DEGREE OF FREEDOM VIBRATION SYSTEM
# ---------------------------------------------------

def undamped_system_ode(y, t, m1, m2, k1, k2, k3):

    x1, v1, x2, v2 = y

    dx1dt = v1

    dv1dt = (
        -k1 * x1
        -k2 * (x1 - x2)
    ) / m1

    dx2dt = v2

    dv2dt = (
        -k3 * x2
        -k2 * (x2 - x1)
    ) / m2

    return [dx1dt, dv1dt, dx2dt, dv2dt]

# Solve undamped system
solution_undamped = odeint(
    undamped_system_ode,
    initial_conditions,
    t,
    args=(m1, m2, k1, k2, k3)
)

# Extract displacements
x1_undamped = solution_undamped[:, 0]
x2_undamped = solution_undamped[:, 2]

# ---------------------------------------------------
# PLOT 1 : UNDAMPED 2-DOF VIBRATION SYSTEM
# ---------------------------------------------------

plt.figure(figsize=(10, 5))

plt.plot(t, x1_undamped, label='Mass 1')
plt.plot(t, x2_undamped, label='Mass 2')

plt.xlabel('Time')
plt.ylabel('Displacement')

plt.title('Undamped Two Degree of Freedom Vibration System')

plt.legend()
plt.grid()

# ---------------------------------------------------
# PLOT 2 : DAMPED 2-DOF VIBRATION SYSTEM
# ---------------------------------------------------

plt.figure(figsize=(10, 5))

plt.plot(t, x1_damped, label='Mass 1 (Damped)')
plt.plot(t, x2_damped, label='Mass 2 (Damped)')

plt.xlabel('Time')
plt.ylabel('Displacement')

plt.title('Damped Two Degree of Freedom Vibration System')

plt.legend()
plt.grid()

# ---------------------------------------------------
# SHOW BOTH PLOTS
# ---------------------------------------------------

plt.show()